### ISSUE TITLE
story: actor based DSL for TFGrid

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/grid3_clientv#1]
# story: actor based client for TFGrid

Actor based development is the way how to do large scale automation and sysadmin, we want to use V to create a client which supports this mechanism. 

## some concepts

- DSL = domain specific language
- ACTOR based paradigm see https://doc.akka.io/docs/akka/current/typed/guide/actors-intro.html for an intro of some of the concepts and https://www.reactivemanifesto.org/ 

## deliverables

- a very well defined DSL
- all used models in ZOS and TFGrid for provisioning documented in V  (structs, autogen docs)
- create actor methods which use those models, document those methods well also using V
- the generated documentation is easy to read
- the actors and models are complete: TFChain, ZOS delivery, TFProxy, TFHub, ... anything relevant to the TFGrid ecosystem

## technical

- expose the actor methods over redis  (simple queue RPC mechanism)
- the actors talk to each other using NATS (through the redis)
- make a proxy between redis and NATS and TF RMB as backend messaging framework
- make a proxy in TS for Stellar/TFChain which is using same redis
- the actor SDK using the models and methods use only redis queues to talk to the outside world

**Comment by despiegk** [comment]
step 1 is to define all models & actors
just as set of structs, there is a go to v convertor which can prob be used to do some of the work

**Comment by sabrinasadik** [comment]
@despiegk let's talk about this

**Comment by despiegk** [comment]
can be closed for now
